apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: make-sample-app-task
spec:
  params:
    - name: app-path
      description: Path to sample-app
  workspaces:
    - name: src
  steps:
    - name: make-build
      image: "cgregistry.capgroup.com/registry.redhat.io/rhel8/go-toolset:1.13.4"
      workingDir: $(workspaces.src.path)/$(params.app-path)
      command: ["/usr/bin/make"]
      args:
        - "build"
    