apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-increment-commit
spec:
  params:
  - name: repo-url
    type: string
  - name: git-branch
    type: string
  - name: image-name
    type: string
  - name: app-path
    type: string
  - name: app-config-path
    type: string
  - name: app-config-filename
    type: string
  - name: image-version
    type: string
  workspaces:
  - name: gitops-workshop-repo-source
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.git-branch) 
      - name: deleteExisting
        value: "true"
    workspaces:
      - name: output
        workspace: gitops-workshop-repo-source
  - name: make-sample-app
    taskRef:
      name: make-sample-app-task
    params:
      - name: app-path
        value: $(params.app-path)
    runAfter:
      - git-clone
    workspaces:
      - name: src
        workspace: gitops-workshop-repo-source
  # - name: build-image
    # taskRef:
      # name: buildah
    # runAfter:
      # - make-sample-app
    # params:
      # - name: IMAGE
        # value: $(params.image-name):$(params.image-version)
      # - name: DOCKERFILE
        # value: $(workspaces.source.path)/$(params.app-path)/Dockerfile
    # workspaces:
    # - name: source
      # workspace: gitops-workshop-repo-source  
  - name: version-increment
    taskRef:
      name: version-increment-task
    runAfter:
      #- build-image
      - make-sample-app
    workspaces:
      - name: src
        workspace: gitops-workshop-repo-source
    params:
      - name: image-name
        value: $(params.image-name)
      - name: image-version
        value: $(params.image-version)
      - name: app-config-path
        value: $(params.app-config-path)
      - name: app-config-filename
        value: $(params.app-config-filename)
  - name: git-commit
    taskRef:
      name: git-cli
    params:
      - name: GIT_USER_NAME
        value: "SkylarScaling"
      - name: GIT_USER_EMAIL
        value: "skylar@redhat.com"
      - name: GIT_SCRIPT
        value: |
          git checkout $(params.git-branch)
          git status
          git add $(params.app-config-path)/$(params.app-config-filename)
          git commit -m "Pipeline execution and version update: $(params.image-name)/$(params.image-version)"
          git push
    runAfter:
      - version-increment
    workspaces:
      - name: source
        workspace: gitops-workshop-repo-source
      - name: input
        workspace: gitops-workshop-repo-source
    
    
