apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-increment-merge
spec:
  params:
  - name: repo-url
    type: string
  - name: git-branch
    type: string
  - name: image-name
    type: string
  - name: app-path
    type: string
  workspaces:
  - name: gitops-workshop-repo-source
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.git-branch) 
      - name: deleteExisting
        value: "true"
    workspaces:
      - name: output
        workspace: gitops-workshop-repo-source
  - name: build-image
    taskRef:
      name: buildah
    runAfter:
      - git-clone
    params:
      - name: IMAGE
        value: $(params.image-name) 
      - name: DOCKERFILE
        value: $(workspaces.source.path)/$(params.app-path)/Dockerfile
    workspaces:
    - name: source
      workspace: gitops-workshop-repo-source  
