apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: gitops-workshop-pipeline-run-argocd
spec:
  pipelineRef:
    name: build-increment-commit
  workspaces:
    - name: gitops-workshop-repo-source
      persistentVolumeClaim:
        claimName: git-clone-output
  params:
    - name: repo-url
      value: https://github.com/darthlukan/gitops-workshop
    - name: git-branch
      value: master
    - name: image-name
      value: quay.io/sscaling/gitops-workshop
    - name: image-version
      value: v0.0.1
    - name: app-path
      value: sample-app
    - name: app-config-path
      value: sample-app-config
    - name: app-config-filename
      value: sample-app-deployment.yaml