---
- name: Making Changes to sample-app-deployment.yaml
  hosts: local
  tasks:
    - name: Replace 'participant' with {{ participant }}
      replace:
        path: "{{ playbook_dir }}/../{{ participant }}-sample-app-config/sample-app-deployment.yaml"
        regexp: 'participant'
        replace: "{{ participant }}"
      register: replaced

    - name: Commit and push to {{ participant }} branch
      shell: |
        git add {{ playbook_dir }}/../{{ participant }}-sample-app-config/sample-app-deployment.yaml && \
        git commit -m 'update greeting' && \
        git push -u origin {{ participant }}
      when: replaced.changed
...
